[package]
name = "steamengine-backend-defaults"
edition = "2024"
authors = ["k3nder <k3nder@outlook.es>"]

[dependencies]
rkyv = "0.8.10"
steamengine-communication = { version = "1.0.0", path = "../steamengine-communication" }
thiserror = "2.0.12"
tracing = "0.1.41"

