[package]
name = "steamengine"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["K3nder <k3nde@outlook.es>"]
description = "A lightweight graphic engine"

[dependencies]
crossbeam-channel = "0.5.15"
env_logger = "0.11.8"
log = "0.4.27"
wgpu = "25.0.0"
winit = "0.29"
