[workspace]
resolver = '2'
members = [
    "client/steamengine-wgpu-core",
    "client/steamengine",
    "backend/steamengine-communication",
    "backend/steamengine-persistent",
    "backend/steamengine-server"
]
