[package]
name = "steamengine"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["K3nder <k3nde@outlook.es>"]
description = "A lightweight graphic engine"

[dependencies]
crossbeam-channel = "0.5.15"
