[package]
name = "instance-test"
version = "0.0.0"
publish = false
edition = "2021"
license = "MIT"

[dependencies]
steamengine-core = { version = "0.1.0", path = "../../steamengine-core" }
bytemuck = "1.23.0"
env_logger = "0.11.8"
pollster = "0.4.0"
cgmath = "0.18.0"
log = "0.4.27"
